# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.
require 'database_cleaner'
require 'cucumber/rails'

ActionController::Base.allow_rescue = false
DatabaseCleaner.allow_remote_database_url = true

# Настройка DatabaseCleaner перед каждым тестом
Before do
  DatabaseCleaner.strategy = :truncation
  DatabaseCleaner.start
end

# Очистка базы данных после каждого теста
After do
  DatabaseCleaner.clean
end

# Possible values are :truncation and :transaction
# The :transaction strategy is faster, but might give you threading problems.
# See https://github.com/cucumber/cucumber-rails/blob/master/features/choose_javascript_database_strategy.feature
Cucumber::Rails::Database.javascript_strategy = :truncation
