version: '3.8'
services:
  web:
    build: .
    command: ./bin/rails server -b 0.0.0.0 -p 3001
    volumes:
      - .:/rails
    ports:
      - "3001:3001"
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db/chat_app
      REDIS_URL: redis://redis:6380/1

  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: chat_app
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: "redis:7-alpine"
    command: redis-server --port 6380
    ports:
      - "6380:6380"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
