development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6380/1" } %>
  channel_prefix: chat_app_bootstrap_development

test:
  adapter: test
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6380/1" } %>
  channel_prefix: chat_app_bootstrap_test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6380/1" } %>
  channel_prefix: chat_app_bootstrap_production
