default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: db
  username: <%= ENV['DB_USERNAME'] || 'rail' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || '123' %>

development:
  <<: *default
  database: chat_app_bootstrap_development

test:
  <<: *default
  database: chat_app_bootstrap_test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %
